package com.splittrip.ui.screens.report

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.splittrip.data.entities.Trip
import com.splittrip.data.repository.SplitTripRepository
import com.splittrip.data.repository.TripReport
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ReportViewModel @Inject constructor(
    private val repository: SplitTripRepository,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val tripId: String = checkNotNull(savedStateHandle["tripId"])

    private val _report = MutableStateFlow<TripReport?>(null)
    val report: StateFlow<TripReport?> = _report.asStateFlow()

    val trip: StateFlow<Trip?> = flow { emit(repository.getTripById(tripId)) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), null)

    private val _isLoading = MutableStateFlow(true)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    init {
        loadReport()
    }

    fun loadReport() {
        viewModelScope.launch {
            _isLoading.value = true
            _report.value = repository.generateSettlements(tripId)
            _isLoading.value = false
        }
    }

    fun generateShareText(): String {
        val tripReport = _report.value ?: return ""
        val tripName = trip.value?.tripName ?: "Trip"
        val currency = trip.value?.currency ?: "USD"
        val sb = StringBuilder()

        sb.appendLine("📊 $tripName - Settlement Report")
        sb.appendLine("=" .repeat(35))
        sb.appendLine()

        if (tripReport.settlements.isEmpty()) {
            sb.appendLine("✅ All balances are settled!")
        } else {
            sb.appendLine("💸 Payments to Make:")
            tripReport.settlements.forEach { s ->
                sb.appendLine("  ${s.fromMemberName} → ${s.toMemberName}: $currency ${String.format("%.2f", s.amount)}")
            }
        }

        sb.appendLine()
        sb.appendLine("📈 Individual Summary:")
        tripReport.memberSummaries.forEach { ms ->
            sb.appendLine("  ${ms.member.name}")
            sb.appendLine("    Paid: $currency ${String.format("%.2f", ms.totalPaid)}")
            sb.appendLine("    Spent: $currency ${String.format("%.2f", ms.totalConsumed)}")
            val balance = ms.balance
            val balStr = if (balance >= 0) "Gets back $currency ${String.format("%.2f", balance)}"
                         else "Owes $currency ${String.format("%.2f", -balance)}"
            sb.appendLine("    $balStr")
        }
        sb.appendLine()
        sb.appendLine("Generated by SplitTrip App")

        return sb.toString()
    }
}
